import test from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {mkdtemp,rm,readFile} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {io} from 'socket.io-client';
import {createSecureClient} from '../bots/secure-client.js';

test('encrypted chat, game, images, authorization, replay rejection and 1 MiB BOT source', {timeout:30000},async t=>{
  const dir=await mkdtemp(path.join(os.tmpdir(),'junqi-secure-')),base='http://127.0.0.1:32168';
  const child=spawn(process.execPath,['server/server.js'],{env:{...process.env,PORT:'32168',SIGUO_DATA_DIR:dir, SIGUO_ROOMS_FILE:path.join(dir,'rooms.json'), SIGUO_PICTURES_DIR:path.join(dir,'pictures'), SIGUO_AVATARS_DIR:path.join(dir,'avatars'),SIGUO_PICTURES_DIR:path.join(dir,'pictures'),SIGUO_PICTURES_LIMIT_BYTES:'1024',ADMIN_KEY:'test-long-key-123'}});
  const sockets=[];let logs='';child.stderr.on('data',b=>logs+=b);
  t.after(async()=>{for(const s of sockets)s.disconnect();if(child.exitCode===null){child.kill();await new Promise(r=>child.once('exit',r));}await rm(dir,{recursive:true,force:true});});
  await new Promise((resolve,reject)=>{child.stdout.on('data',b=>{if(String(b).includes('已启动'))resolve();});child.once('exit',()=>reject(Error(logs)));});
  const admin=createSecureClient(base),a=createSecureClient(base),b=createSecureClient(base),anonymous=createSecureClient(base);
  async function call(client,route,body,headers={},method){return client.fetch(route,{method:method||(body?'POST':'GET'),headers:{'Content-Type':'application/json',...headers},body:body?JSON.stringify(body):undefined});}
  assert.equal((await fetch(base+'/api/admin/chat')).status,426);
  assert.equal((await call(anonymous,'/api/admin/chat')).status,403);
  for(const username of ['alice','bob','robot'])assert.equal((await call(admin,'/api/admin/accounts',{username,password:'test1234',accountType:username==='robot'?'bot':'human'},{'x-admin-key':'test-long-key-123'})).status,201);
  const tokenA=(await(await call(a,'/api/login',{username:'alice',password:'test1234'})).json()).token;
  const tokenB=(await(await call(b,'/api/login',{username:'bob',password:'test1234'})).json()).token;
  const headersA={Authorization:`Bearer ${tokenA}`},headersB={Authorization:`Bearer ${tokenB}`};
  async function connect(client){
    const socket=io(base,{autoConnect:false,reconnection:false,transports:['websocket'],auth:{id:(await client.channel()).id,proof:await client.seal({kind:'socket'})}});
    sockets.push(socket);socket.messages=[];let queue=Promise.resolve();
    socket.on('sealed',packet=>{queue=queue.then(async()=>{const data=await client.open(packet);socket.messages.push(data);});});
    socket.sendEvent=async(event,...args)=>socket.emit('sealed',await client.seal({kind:'event',event,args}));
    socket.wait=async(event,predicate=()=>true)=>{for(let i=0;i<300;i++){const index=socket.messages.findIndex(m=>m.event===event&&predicate(m.args[0]));if(index>=0)return socket.messages.splice(index,1)[0].args[0];await new Promise(r=>setTimeout(r,10));}throw Error('Timeout '+event+' '+logs);};
    await new Promise((resolve,reject)=>{socket.once('connect',resolve);socket.once('connect_error',reject);socket.connect();});return socket;
  }
  const sa=await connect(a),sb=await connect(b),sn=await connect(anonymous);
  await sa.sendEvent('lobby-auth',{authToken:tokenA});await sa.wait('lobby-chat');
  await sa.sendEvent('lobby-chat-message',{authToken:tokenA,text:'secret lobby'});await sa.wait('lobby-chat',m=>m.some(x=>x.text==='secret lobby'));
  assert.equal(sn.messages.some(m=>m.event==='lobby-chat'),false);
  assert.equal((await(await call(admin,'/api/admin/chat',null,{'x-admin-key':'test-long-key-123'})).json()).messages[0].text,'secret lobby');
  await sa.sendEvent('create-room',{authToken:tokenA,capacity:2});const session=await sa.wait('session');
  await sa.wait('room-state');
  const png='iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aE1sAAAAASUVORK5CYII=';
  const upload=await call(a,'/api/images',{scope:session.code,data:png},headersA);assert.equal(upload.status,200);const image=(await upload.json()).url;
  assert.equal((await call(b,image,null,headersB)).status,403);
  assert.equal((await call(anonymous,image)).status,403);
  assert.equal((await(await call(a,image,null,headersA)).json()).data,png);
  const entries=JSON.parse(await readFile(path.join(dir,'pictures/siguo-images.json')));assert.equal(entries.length,1);
  assert.equal((await readFile(path.join(dir,`pictures/siguo-${entries[0].id}.img`))).toString('base64'),png);
  await sb.sendEvent('join-room',{authToken:tokenB,code:session.code});await sb.wait('session');
  assert.equal((await call(b,image,null,headersB)).status,200);
  await sa.sendEvent('chat-message',{text:`secret room ![](${image})`});await sb.wait('room-state',r=>r.chat.some(m=>m.text.startsWith('secret room')));
  await sb.sendEvent('take-seat',{seat:'south'});await sb.wait('session',s=>s.seat==='south');
  await sa.sendEvent('toggle-ready');await sb.sendEvent('toggle-ready');await sa.wait('room-state',r=>r.players.every(p=>p.ready));
  await sa.sendEvent('start-game');const started=await sa.wait('room-state',r=>r.phase==='playing');assert.ok(started.pieces.some(p=>!p.type));
  const repeat=await a.seal({kind:'event',event:'chat-message',args:[{text:'once only'}]});sa.emit('sealed',repeat);await sa.wait('room-state',r=>r.chat.some(m=>m.text==='once only'));sa.emit('sealed',repeat);await sa.wait('game-error');
  const tamper=await a.seal({kind:'event',event:'resign',args:[]});tamper.data='AAAA'+tamper.data.slice(4);sa.emit('sealed',tamper);await sa.wait('game-error');
  await sb.sendEvent('leave-room');await sa.wait('room-state',r=>!r.players.some(p=>p.name==='bob'&&p.online));
  assert.equal((await call(b,image,null,headersB)).status,403);
  const robotToken=(await(await call(admin,'/api/login',{username:'robot',password:'test1234'})).json()).token;
  const prefix='function act(){return {action:"ready",ready:true}}\n/*',suffix='*/';
  const source=prefix+'x'.repeat(1024*1024-prefix.length-suffix.length)+suffix;
  const botHeaders={Authorization:`Bearer ${robotToken}`};
  assert.equal((await call(admin,'/api/program',{source},botHeaders,'PUT')).status,200);
  assert.equal((await call(admin,'/api/program',{source:source+'x'},botHeaders,'PUT')).status,400);
  // Execute the actual browser transport module with WebCrypto and Socket.IO.
  globalThis.window={fetch:(url,options)=>globalThis.fetch(new URL(url,base),options)};
  globalThis.location={href:base+'/',origin:base};globalThis.io=options=>io(base,options);
  globalThis.alert=message=>{throw Error(message);};
  const browser=await import('../public/secure.js');
  assert.equal((await browser.secureFetch('/api/me',{headers:headersA})).status,200);
  const ui=browser.secureSocket();sockets.push(ui);
  await new Promise((resolve,reject)=>{ui.once('connect',resolve);ui.once('connect_error',reject);});
  const history=new Promise(resolve=>ui.once('lobby-chat',resolve));ui.emit('lobby-auth',{authToken:tokenA});assert.ok((await history).some(m=>m.text==='secret lobby'));
  const ack=await new Promise(resolve=>ui.timeout(2000).emit('leave-room',(error,value)=>resolve({error,value})));
  assert.equal(ack.error,null);assert.equal(ack.value.ok,true);
  ui.disconnect();
  await call(a,'/api/logout',{},headersA);
  assert.equal((await call(a,image,null,headersA)).status,403);
  for(let i=0;i<5;i++)assert.equal((await call(b,'/api/images',{scope:'lobby',data:png},headersB)).status,200);
  const index=await readFile(path.join(dir,'pictures/siguo-images.json'));
  assert.ok(JSON.parse(index).reduce((sum,item)=>sum+item.size,index.length)<=1024);
  assert.equal((await call(b,image,null,headersB)).status,404);
  assert.equal((await fetch(base+'/socket.io/?EIO=4&transport=polling',{headers:{Origin:'https://untrusted.example'}})).status,403);
  for(let i=0;i<9;i++)assert.equal((await call(b,'/api/login',{username:'missinguser',password:'incorrect'})).status,401);
  assert.equal((await call(b,'/api/login',{username:'missinguser',password:'incorrect'})).status,429);
});
